---
- hosts: localhost
  tasks:
  - name: Fetch bash-it repository
    git:
      repo: https://github.com/Ghrind/bash-it.git
      dest: /home/{{ansible_user_id}}/.bash-it
      accept_hostkey: true
  - name: Install bash-it
    command: /home/{{ansible_user_id}}/.bash-it/install.sh --silent

  - name: Configure bashit
    command: bash-it disable aliases general && bash-it enable aliases grinder

  - name: Install ag silversearcher
    pacman:
      name: the_silver_searcher
      state: latest
    become: true

  - name: Install fzf
    pacman:
      name: fzf
      state: latest
    become: true
  - name: Copy the fzf bash file
    copy:
      src: "{{playbook_dir}}/resources/.fzf.bash"
      dest: /home/{{ansible_user_id}}/.fzf.bash
  - name: Enable fzf for bashit
    command: bash-it search fzf --enable
  - name: Install autojump
    pacman:
      name: autojump
      state: latest
    become: true
  - name: Enable autojump for bashit
    command: bash-it search autojump --enable
