---
- hosts: localhost
  vars_prompt:
  - name: ssh_passphrase
    private: yes
  tasks:
  - name: Generate SSH keys
    shell: ssh-keygen -b 2048 -t rsa -f /home/{{ansible_user_id}}/.ssh/id_rsa -q -N "{{ssh_passphrase}}"
    args:
      creates: /home/{{ansible_user_id}}/.ssh/id_rsa
