---
- hosts: localhost
  tasks:
  - name: Install Vim package (with clipboard support)
    pacman:
      name: gvim
      state: latest
    become: true
  - name: Install Vim Dotfiles
    git:
      repo: https://github.com/Ghrind/dotvim.git
      dest: /home/{{ansible_user_id}}/.vim
      accept_hostkey: true
  - name: Create .vimrc Symlink
    file:
      src: /home/{{ansible_user_id}}/.vim/vimrc
      dest: /home/{{ansible_user_id}}/.vimrc
      state: link
